version: '3.9'

services:
  backend-dev:
    image: car-plate-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - 8000:8000
    stdin_open: true
